name: Continuous testing

on: [pull_request]

jobs:
  dismiss-reviews:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss Approvals
        env:
          GH_TOKEN: ${{ github.token }}
        run:  |
          gh api repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews \
          --jq '.[] | select(.state == "APPROVED") | .id' \
          | xargs -I '{}' gh api --method=PUT -f message="Dismissed due to PR edit." \
          repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews/'{}'/dismissals

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run test
