name: Continuous testing

on: [pull_request]

jobs:
  dismiss-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss Approvals
        run: gh api repos/${{ github.event.repo.name }}/pulls/${{ github.event.number }}/reviews --jq '.[] | [.id,.state] | join("=")' | grep -Po '\d+(?=\=APPROVED)' | xargs -I '@(review_id)' gh api repos/${{ github.event.repo.name }}/pulls/${{ github.event.number }}/reviews/@(review_id)/dismissals
        env:
          GH_TOKEN: ${{ github.token }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run test
